server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: root1007
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      import-check:
        enabled: false
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: "SuperSecretKeyStreamPluse123456789"
  expiration: 86400000  # 24 часа
  
logging:
  level:
    org.springframework: INFO
    com.akobir.authservice: DEBUG