server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**  
          # ❌ убираем фильтр для публичных путей
          # filters:
          #   - name: JwtAuthFilter

        - id: other-service
          uri: lb://other-service
          predicates:
            - Path=/api/v1/other/**  
          filters:
            - name: JwtAuthFilter  # защищённые маршруты

jwt:
  secret: "dbfe01982367482949bcef6ff02bf67d"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
