server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: dbfe01982367482949bcef6ff02bf67d
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: JwtAuthFilter  # 👈 фильтр

jwt:
  secret: "dbfe01982367482949bcef6ff02bf67d"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
