server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
          filters:
            - name: JwtAuthFilter

        - id: other-service
          uri: lb://other-service
          predicates:
            - Path=/api/v1/other/**  
          filters:
            - name: JwtAuthFilter  # защищённые маршруты

jwt:
  secret: "dbfe01982367482949bcef6ff02bf67d"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
